# Generated by Django 3.0.5 on 2024-12-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20241223_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answers',
            field=models.TextField(default={1}),
            preserve_default=False,
        ),
    ]
